Specialty.create(name: 'cardiologia')
Specialty.create(name: 'psiquiatria')
Specialty.create(name: 'psicologia')
Role.create(name: 'doctor')
Role.create(name: 'enfermera')
Role.create(name: 'secretaria')
AdminUser.create!(email: 'admin@gmail.com', password: 'password', password_confirmation: 'password')